name: gp2
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.10.0 # Google Maps for map functionalities
  geolocator: ^13.0.2          # To fetch the user's location
  geocoding: ^3.0.0            # For reverse geocoding (LatLng to address)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
